name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy apps.json, build image and push it to GHCR
      run: |
        export APPS_JSON_BASE64=$(base64 -w 0 -i apps.json)
        docker build --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe --build-arg=FRAPPE_BRANCH=version-15 --build-arg=PYTHON_VERSION=3.10.12 --build-arg=NODE_VERSION=18.12.0 --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 --tag=ghcr.io/as-kilta/erpnext:latest --file=Containerfile .
        docker push ghcr.io/as-kilta/erpnext:latest
