name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: export APPS_JSON_BASE64=$(base64 -w 0 -i apps.json)

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/as-kilta/erpnext:latest
        file: Containerfile
        build-args: |
          FRAPPE_PATH=https://github.com/frappe/frappe
          FRAPPE_BRANCH=version-15
          PYTHON_VERSION=3.10.12
          NODE_VERSION=18.12.0
          APPS_JSON_BASE64=$APPS_JSON_BASE64
